name = "it-service-desk"
compatibility_date = "2024-08-30"
pages_build_output_dir = "./dist"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "it-service-desk-db"
database_id = "d676dc2d-0eb7-4f5a-8d73-a1940b8c6241"

# [ai]
# binding = "AI"